# Fetching the minified node image on apline linux
FROM node:slim

# Declaring env
ENV NODE_ENV production

# Setting up the work directory
WORKDIR /backend

# Copying all the files in our project
COPY . .

# Install OpenSSL
RUN apt-get update && apt-get install -y openssl

# Installing dependencies
RUN npm install

# Installing pm2 globally
RUN npm install pm2 -g

# Set environment variable for database url
ENV DATABASE_URL postgresql://postgres:postgres@project2-db:5432/dishesdb?schema=public

# Starting our application
CMD pm2 start process.yml && tail -f /dev/null

# Exposing server port
EXPOSE 4000