import { test, expect } from '@playwright/test';

/* 
  An e2e test to ensure keyboard navigation is possible. Includes standard navigation
  around the pages.
*/

test('test', async ({ page }) => {
  await page.goto('http://it2810-43.idi.ntnu.no/project2/');
  await page.getByLabel('Link to homepage of Food Ltd.').click();
  await page.getByLabel('Link to homepage of Food Ltd.').press('Tab');
  await page.getByRole('link', { name: 'Home', exact: true }).press('Tab');
  await page.getByRole('link', { name: 'Settings' }).press('Enter');
  await page.getByRole('link', { name: 'Settings' }).press('Tab');
  await page.getByRole('button', { name: 'Darkmode' }).press('Enter');
  await page.getByRole('button', { name: 'Lightmode' }).press('Tab');
  await page.getByRole('button', { name: 'Fahrenheit' }).press('Enter');
  await expect(page.locator('#root')).toContainText('Lightmode');
  await expect(page.locator('#root')).toContainText('Celsius');
  await page.getByText('Settings').nth(1).click();
  await page.locator('body').press('Tab');
  await page.getByRole('button', { name: 'Lightmode' }).press('Enter');
  await page.getByRole('button', { name: 'Darkmode' }).press('Tab');
  await page.getByRole('button', { name: 'Celsius' }).press('Enter');
  await expect(page.locator('#root')).toContainText('Darkmode');
  await expect(page.locator('#root')).toContainText('Fahrenheit');
  await page.getByText('Settings').nth(1).click();
  await page.locator('body').press('Shift+Tab');
  await page.getByRole('link', { name: 'Settings' }).press('Shift+Tab');
  await page.getByRole('link', { name: 'Home', exact: true }).press('Enter');
  await page.getByRole('link', { name: 'Home', exact: true }).press('Tab');
  await page.getByRole('link', { name: 'Settings' }).press('Tab');
  await page.getByPlaceholder('Search').press('Tab');
  await page.getByTestId('searchsettingsquare').press('Shift+Tab');
  await page.getByPlaceholder('Search').fill('miso');
  await page.getByPlaceholder('Search').press('ArrowDown');
  await page.getByPlaceholder('Search').press('ArrowDown');
  await page.getByPlaceholder('Search').press('ArrowUp');
  await page.getByPlaceholder('Search').press('ArrowUp');
  await page.getByPlaceholder('Search').press('ArrowDown');
  await page.getByPlaceholder('Search').press('ArrowDown');
  await page.getByPlaceholder('Search').press('ArrowUp');
  await page.getByPlaceholder('Search').press('ArrowDown');
  await page.getByPlaceholder('Search').press('ArrowUp');
  await page.getByPlaceholder('Search').press('ArrowDown');
  await page.getByPlaceholder('Search').press('ArrowUp');
  await page.getByPlaceholder('Search').press('ArrowDown');
  await page.getByPlaceholder('Search').press('ArrowUp');
  await page.getByPlaceholder('Search').press('ArrowDown');
  await page.getByPlaceholder('Search').press('ArrowUp');
  await page.getByPlaceholder('Search').press('ArrowDown');
  await page.getByPlaceholder('Search').press('ArrowUp');
  await page.getByPlaceholder('Search').press('ArrowDown');
  await page.getByPlaceholder('Search').press('ArrowUp');
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').press('Enter');
  await page.getByPlaceholder('Search').click();
  await expect(page.locator('#root')).toContainText('Showing results for: "miso"');
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').press('Tab');
  await page.locator('body').press('Tab');
  await page.getByTestId('searchsettingsquare').press('Tab');
  await page.getByRole('button', { name: 'Popular' }).press('Tab');
  await page.getByRole('button', { name: 'Rating' }).press('Tab');
  await page.getByRole('button', { name: 'A-Z' }).press('Tab');
  await page.getByRole('button', { name: '< Prevous' }).press('Tab');
  await page.getByLabel('Go to page number').press('Tab');
  await page.getByRole('link', { name: 'food Miso-Butter Roast' }).press('Enter');
  await page.locator('body').press('Tab');
  await page.getByRole('link', { name: 'Back' }).press('Tab');
  await page.getByRole('link', { name: 'Write a review' }).press('Enter');
  await page.locator('body').press('Tab');
  await page.locator('input[name="title"]').fill('Title of the post');
  await page.locator('input[name="title"]').press('Tab');
  await page.getByTestId('commet-area').fill('Here is a comment');
  await page.getByTestId('commet-area').press('Tab');
  await page.getByRole('button', { name: 'star' }).first().press('Tab');
  await page.getByRole('button', { name: 'star' }).nth(1).press('Tab');
  await page.getByRole('button', { name: 'star' }).nth(2).press('Tab');
  await page.getByRole('button', { name: 'star' }).nth(3).press('Tab');
  await page.getByRole('button', { name: 'star' }).nth(4).press('Enter');
  await page.getByRole('button', { name: 'star' }).nth(4).press('Tab');
  await page.getByRole('button', { name: 'Submit' }).press('Tab');
  await expect(page.locator('form')).toContainText('5');
  await expect(page.getByTestId('commet-area')).toContainText('Here is a comment');
  await page.locator('input[name="title"]').click();
  await page.locator('input[name="title"]').press('Tab');
  await page.getByTestId('commet-area').press('Tab');
  await page.getByRole('button', { name: 'star' }).first().press('Tab');
  await page.getByRole('button', { name: 'star' }).nth(1).press('Tab');
  await page.getByRole('button', { name: 'star' }).nth(2).press('Tab');
  await page.getByRole('button', { name: 'star' }).nth(3).press('Tab');
  await page.getByRole('button', { name: 'star' }).nth(4).press('Tab');
  await page.getByRole('button', { name: 'Submit' }).press('Tab');
  await page.getByRole('link', { name: 'Cancel' }).press('Enter');
  await page.locator('body').press('Shift+Tab');
  await page.getByRole('link', { name: 'Settings' }).press('Shift+Tab');
  await page.getByRole('link', { name: 'Home', exact: true }).press('Tab');
  await page.getByRole('link', { name: 'Settings' }).press('Tab');
  await page.getByRole('link', { name: 'Back' }).press('Enter');
  await page.locator('body').press('Tab');
  await page.getByPlaceholder('Search').press('Tab');
  await page.locator('body').press('Shift+Tab');
  await page.getByRole('link', { name: 'Settings' }).press('Shift+Tab');
  await page.getByRole('link', { name: 'Home', exact: true }).press('Tab');
  await page.getByRole('link', { name: 'Settings' }).press('Tab');
  await page.getByPlaceholder('Search').press('Tab');
  await page.locator('body').press('Shift+Tab');
  await page.getByRole('link', { name: 'Settings' }).press('Tab');
  await page.getByPlaceholder('Search').press('Tab');
  await page.locator('body').press('Shift+Tab');
  await page.getByRole('link', { name: 'Settings' }).press('Tab');
  await page.getByPlaceholder('Search').fill('');
  await page.getByPlaceholder('Search').press('Enter');
  await page.getByPlaceholder('Search').press('Tab');
  await page.getByTestId('searchsettingsquare').press('Tab');
  await page.getByRole('button', { name: 'Popular' }).press('Tab');
  await page.getByRole('button', { name: 'Rating' }).press('Tab');
});