import { Ingredient } from 'src/types/types'

export const SORTING_OPTIONS = {
  Popular: 'popular',
  Rating: 'rating',
  'A-Z': 'alphabetical',
}

export const INCLUDE_FILTER_OPTIONS = [
  'Chicken',
  'Vegetable',
  'Pasta',
  'Cheese',
  'Meat',
]
export const EXCLUDE_FILTER_OPTIONS = [
  'Milk',
  'Egg',
  'Salt',
  'Sugar',
  'Red Pepper',
]
export const SEARCH_TIMEOUT_MS = 500

export const colors = {
  'primary-text': '#000000',
  'grayed-text': '#9ca399',
  selected: '#5fd14f',
  primary: '#FBE6BB',
  secondary: '#E38A35',
  tulip: '#EFB33C',
  flame: '#D7582C',
  oldbrick: '#8A2120',
  primarydark: '#212121',
  secondarydark: '#424242',
  tertiarydark: '#616161',
}

export const INGREDIENTS: Array<Ingredient> = [
  { id: 1, name: 'salt' },
  { id: 2, name: 'pepper' },
  { id: 3, name: 'sugar' },
  { id: 4, name: 'flour' },
  { id: 5, name: 'butter' },
  { id: 6, name: 'olive oil' },
  { id: 7, name: 'garlic' },
  { id: 8, name: 'onion' },
  { id: 9, name: 'egg' },
  { id: 10, name: 'milk' },
  { id: 11, name: 'cream' },
  { id: 12, name: 'cheese' },
  { id: 13, name: 'chicken' },
  { id: 14, name: 'beef' },
  { id: 15, name: 'pork' },
  { id: 16, name: 'fish' },
  { id: 17, name: 'shrimp' },
  { id: 18, name: 'rice' },
  { id: 19, name: 'pasta' },
  { id: 20, name: 'potato' },
  { id: 21, name: 'tomato' },
  { id: 22, name: 'lettuce' },
  { id: 23, name: 'carrot' },
  { id: 24, name: 'broccoli' },
  { id: 25, name: 'bell pepper' },
  { id: 26, name: 'zucchini' },
  { id: 27, name: 'eggplant' },
  { id: 28, name: 'spinach' },
  { id: 29, name: 'cucumber' },
  { id: 30, name: 'celery' },
  { id: 31, name: 'corn' },
  { id: 32, name: 'green beans' },
  { id: 33, name: 'mushroom' },
  { id: 34, name: 'thyme' },
  { id: 35, name: 'rosemary' },
  { id: 36, name: 'oregano' },
  { id: 37, name: 'basil' },
  { id: 38, name: 'parsley' },
  { id: 39, name: 'cumin' },
  { id: 40, name: 'paprika' },
  { id: 41, name: 'cayenne pepper' },
  { id: 42, name: 'turmeric' },
  { id: 43, name: 'cinnamon' },
  { id: 44, name: 'nutmeg' },
  { id: 45, name: 'vanilla extract' },
  { id: 46, name: 'lemon' },
  { id: 47, name: 'lime' },
  { id: 48, name: 'orange' },
  { id: 49, name: 'lemon juice' },
  { id: 50, name: 'lime juice' },
  { id: 51, name: 'soy sauce' },
  { id: 52, name: 'balsamic vinegar' },
  { id: 53, name: 'red wine vinegar' },
  { id: 54, name: 'white wine vinegar' },
  { id: 55, name: 'apple cider vinegar' },
  { id: 56, name: 'mustard' },
  { id: 57, name: 'ketchup' },
  { id: 58, name: 'mayonnaise' },
  { id: 59, name: 'sour cream' },
  { id: 60, name: 'yogurt' },
  { id: 61, name: 'hot sauce' },
  { id: 62, name: 'salsa' },
  { id: 63, name: 'maple syrup' },
  { id: 64, name: 'honey' },
  { id: 65, name: 'chili powder' },
  { id: 66, name: 'cocoa powder' },
  { id: 67, name: 'bread crumbs' },
  { id: 68, name: 'vegetable broth' },
  { id: 69, name: 'chicken broth' },
  { id: 70, name: 'beef broth' },
  { id: 71, name: 'vegetable stock' },
  { id: 72, name: 'chicken stock' },
  { id: 73, name: 'beef stock' },
  { id: 74, name: 'black beans' },
  { id: 75, name: 'kidney beans' },
  { id: 76, name: 'pinto beans' },
  { id: 77, name: 'garbanzo beans' },
  { id: 78, name: 'lentils' },
  { id: 79, name: 'quinoa' },
  { id: 80, name: 'couscous' },
  { id: 81, name: 'oats' },
  { id: 82, name: 'almonds' },
  { id: 83, name: 'cashews' },
  { id: 84, name: 'peanuts' },
  { id: 85, name: 'walnuts' },
  { id: 86, name: 'sunflower seeds' },
  { id: 87, name: 'chia seeds' },
  { id: 88, name: 'flax seeds' },
  { id: 89, name: 'coconut milk' },
  { id: 90, name: 'coconut oil' },
  { id: 91, name: 'canned tomatoes' },
  { id: 92, name: 'tomato paste' },
  { id: 93, name: 'tomato sauce' },
  { id: 94, name: 'canned corn' },
  { id: 95, name: 'diced potatoes' },
  { id: 96, name: 'frozen peas' },
  { id: 97, name: 'frozen corn' },
  { id: 98, name: 'frozen broccoli' },
  { id: 99, name: 'frozen spinach' },
  { id: 100, name: 'frozen mixed vegetables' },
  { id: 101, name: 'frozen strawberries' },
  { id: 102, name: 'frozen blueberries' },
  { id: 103, name: 'frozen raspberries' },
  { id: 104, name: 'frozen mango' },
  { id: 105, name: 'frozen pineapple' },
  { id: 106, name: 'canned tuna' },
  { id: 107, name: 'canned salmon' },
  { id: 108, name: 'canned sardines' },
  { id: 109, name: 'canned chicken' },
  { id: 110, name: 'canned black olives' },
  { id: 111, name: 'canned green olives' },
  { id: 112, name: 'canned artichoke hearts' },
  { id: 113, name: 'canned mushrooms' },
  { id: 114, name: 'canned pimentos' },
  { id: 115, name: 'canned coconut cream' },
  { id: 116, name: 'canned pineapple chunks' },
  { id: 117, name: 'canned mandarin oranges' },
  { id: 118, name: 'canned peaches' },
  { id: 119, name: 'canned pears' },
  { id: 120, name: 'canned cherries' },
]
